### PR TITLE
Add more reviewers

### PR DESCRIPTION
**Pull request by sideninja**
Add more reviewers on build bundle action so it doesn't get stale.

### CODE REVIEW

**Comment by bluesign** [comment]
does it even need review ? was there any case that PR should not be approved?

**Comment by sideninja** [comment]
Repo settings requires it

**Review by justinbarry — APPROVED** [review]
lgtm

**Comment by justinbarry** [comment]
@sideninja Is it possible to use GH teams here? I'll approve it but might be worth looking into.

**Pull request merged**
