### PR TITLE
Improvement to the integration process

### PR DESCRIPTION
**Pull request by sideninja**
During the development of this feature I've also realised the pain for constant updating the Go library with new configuration values as they are added in FCL dev wallet. So I worked on making sure this need is removed. Go server now dynamically builds the config provided in .env.development. So if there are new configuration values you just need to make sure you add them to the .env.development. It also solves the problem of having two copies of config, one for development and running dev wallet with next and one for running dev wallet with Go and in CLI. Both now use the .env config.

This PR changes the functioning of configuration implementation. It now dynamically builds the config from two sources:
- From the configuration passed to the library 
- From the `.env.development` file

The configuration that is being passed to the library will overwrite the configuration 
in the `.env.development` but it's only limited to providing values for the following keys:
- `flowAccountAddress`
- `flowAccountPrivateKey`
- `flowAccountPublicKey`
- `flowAccessNode`

The configuration that is fetched from the `.env.development` file will be converted from 
snake case to camel case. Example a property named `FOO_BAR_ZOO` wil become `fooBarZoo` 
when server with the API configuration endpoint.

Configuration is dynamically built, so even if new values are added there is no change 
required in the Go implementation, beside just building the bundle and releasing a new version 
on the Github.

### Testing
During the development of Dev wallet you can test how the Go library works by running:
```
npm run go-server
```
This command will build the latest bundle, copy the `.env.development` from the root 
directory in the `/go/wallet` (just to make sure they are in sync), build the Go server and 
run it. **You must make sure you have Go installed**, here are instructions: https://go.dev/doc/install

### CODE REVIEW

**Comment by sideninja** [comment]
@gregsantos @justinbarry have you checked this?

**Comment by gregsantos** [comment]
HUGE improvements here @sideninja TY!

**Review by gregsantos — COMMENTED** [review]
Looking forward to these improvements 🚀
When I run `npm run go-server` the build/zip/config pipeline seems to go well, but when visiting `http://localhost:8701/` instead of seeing the harness, I get a dir listing with the `/out` path

**Comment by sideninja** [comment]
> Looking forward to these improvements 🚀 When I run `npm run go-server` the build/zip/config pipeline seems to go well, but when visiting `http://localhost:8701/` instead of seeing the harness, I get a dir listing with the `/out` path

Oh, my apologies. I didn't see that during testing since I had the correct zip in the first run and then it wasn't replaced. Which was another problem I found now. Both should be fixed.

**Comment by gregsantos** [comment]
No prob. 
Needing to run `go get github.com/onflow/fcl-dev-wallet/go/wallet` as well to get the server running. 
"Missing go.sum entry for module providing package..."
Should/can that be added to the pipeline?

**Comment by gregsantos** [comment]
Once server is running, I'm afraid, we're still getting errors on the first call to the emulator:

Error: INVARIANT SDK Send Error: Either opts.node or "accessNode.api" in config must be defined. Echos of the config var issue. Is `accessNode` getting set I wonder?

**Comment by sideninja** [comment]
> No prob. Needing to run `go get github.com/onflow/fcl-dev-wallet/go/wallet` as well to get the server running. "Missing go.sum entry for module providing package..." Should/can that be added to the pipeline?

This is more of a Go installation thing, it doesn't need to be run every time you run the server. It can however be added to the readme.

**Comment by justinbarry** [comment]
@sideninja I had to run that command as well.

**Pull request merged**
