### PR TITLE
Update fcl and modify refresh endpoint to work with any user

### LINKED ISSUE #91: Refresh endpoint always returns service account auth
The refresh endpoint always returns the service account address: https://github.com/onflow/fcl-dev-wallet/blob/main/pages/api/refresh.ts#L38

This means that whenever I try to create a new transaction using `fcl.mutate()`, the current user changes to the service account. This makes it impossible to sign transactions with any other account.

This doesn't repro in the test harness because the version of `onflow/fcl` we're using doesn't implement refresh yet.

### PR DESCRIPTION
**Pull request by alse**
- updates fcl to 0.0.79-alpha.2
- adds sdk.transport config
- updates the refresh endpoint to work with any user
- fixes #91

Tested with KittyItems on dev

### CODE REVIEW

**Comment by alse** [comment]
@gregsantos how does this look?

**Comment by gregsantos** [comment]
Thanks @alse 
Looks like you are returning same response as `prove-authn`.
The refresh service endpoint should return same data as [accountAuth](https://github.com/onflow/fcl-dev-wallet/blob/main/src/accountAuth.ts)
It's designed to check the user's session and refresh if necessary, returning updated authentication configuration for FCL (address, services, etc.)
Since dev-wallet has no idea of "session" it should just return the same response as initial authentication but via the api endpoint.
```javascript
const response = {
  f_type: "PollingResponse",
  f_vsn: "1.0.0",
  status: "APPROVED",
  data: {
    f_type: "AuthnResponse",
    f_vsn: "1.0.0",
    addr: address,
    services: services,
  },
}
```

The issue is that currently it's using the service address and should use the user's address.
Does this make sense?

**Comment by alse** [comment]
Thanks @gregsantos , I updated it to return the same response as the intial auth. Confirmed that all the user details except account-proof.signature remain the same after a refresh.

**Review by gregsantos — APPROVED** [review]
Updating package-lock did the trick on that styles issue. Thanks for picking this up!

**Comment by alse** [comment]
No worries, merging this in!

**Pull request merged**
